Chanzhaoyu/chatgpt-web

src/views/chat/components/Message/Avatar.vue

feat: 应用自定义头像

---

.vscode/settings.json
package.json
pnpm-lock.yaml
src/plugins/assets.ts
src/views/chat/components/Message/Text.vue

feat: add latex rendering

---

README.md

添加打字机效果故障的一种解决方案。ref: https://github.com/Chanzhaoyu/chatgpt-web/issues/259

chore: 更新文档常见问题

---

package.json
pnpm-lock.yaml
src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts
src/views/chat/index.vue

feat: 增加保存会话为图片的功能

---

src/components/common/PromptStore/index.vue

增加特定键检查
感谢 https://github.com/Chanzhaoyu/chatgpt-web/issues/516 提出的issue

fix: 更新JSON导入检查

---

service/package.json
service/src/index.ts

修复设置了`AUTH_SECRET_KEY`的情况下的跨域异常。

fix: 修复AUTH_SECRET_KEY模式下跨域异常并添加对node.js 19版本的支持

---

Dockerfile

* 1. speed up building for every time
* 2. reduce docker image size

chore: optimize dockerfile 

---

src/router/permission.ts

fix: inverted parameter for before each function

---

src/components/common/PromptStore/index.vue

feat: 修改移动端 prompt 商店样式

---

src/assets/recommend.json

Add zh-TW prompts

---

vite.config.ts

PWA插件未push到plugins数组
https://github.com/Chanzhaoyu/chatgpt-web/blob/917feec5d8f4512b26d3bcac7fba6465342e8371/vite.config.ts#L11

fix:PWA未生效问题

---

README.md
pnpm-lock.yaml
service/.env.example
service/pnpm-lock.yaml
service/src/chatgpt/index.ts

feat: allow user disable openai API debug log

---

service/src/index.ts
src/utils/request/index.ts
src/views/chat/components/Message/Text.vue
src/views/chat/index.vue

Simulate the official typing effect, showing the blinking cursor when typing, and gone after typing is complete.

feat: add typing effect

---

kubernetes/README.md
kubernetes/deploy.yaml
kubernetes/ingress.yaml

-  有一些在企业内部部署的方式，可以直接通过kubectl apply的方式进行部署chatgpt-web服务

add kubernetes deploy

---

src/styles/lib/highlight.less

fix: x-scrollbar height

---

service/src/chatgpt/index.ts
service/src/chatgpt/types.ts
src/components/common/Setting/About.vue
src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts

fix: 使API余额查询可用

---

src/locales/zh-TW.ts

Just some minor improvements, thanks!

Improve zh-TW locale

---

src/views/chat/components/Message/Text.vue

[fix] markdown 表格内没有换行

---

src/views/chat/layout/sider/index.vue

fix: 移动端新建会话关闭侧边栏

---

README.md
service/src/chatgpt/index.ts

feat: 支持最新的gpt-3.5-turbo-16k模型

---

src/locales/zh-TW.ts

chore: Improve zh-TW locale

---

src/store/helper.ts
src/store/index.ts
src/store/modules/app/index.ts
src/store/modules/auth/index.ts

fix: store循环引用

---

README.md
README.zh.md
service/src/chatgpt/index.ts

This includes the latest:
- gpt-4-0125-preview
- gpt-4-turbo-preview
Reference:
- https://openai.com/blog/new-embedding-models-and-api-updates

feat: support the latest GPT-4 Turbo preview models

---

service/src/chatgpt/index.ts

see: https://developers.cloudflare.com/ai-gateway/get-started/connecting-applications/#openai

fix(server): compatible with gateway.ai.cloudflare.com

---

README.md
README.zh.md
service/src/chatgpt/index.ts

Reference:
- https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

Add GPT-4 Turbo API the latest GA version
