Chanzhaoyu/chatgpt-web

src/views/Chat/index.vue

部分输入法支持中英文混输，输入过程中按空格选择中文，按回车把当前的英文直接上屏。
至少在Chrome浏览器中，会把输入法选英文词的回车作为keyup事件，导致未输入完成的句子被提交。改成监听keypress事件就没问题了。 其他浏览器未测试。

fix: 防止中文输入法输入英文时触发提交

---

.github/workflows/build_docker.yml
Dockerfile
README.md

新增一些优化和功能：
1. 自动构建 docker
2. 优化构建后的大小 image 的大小
自动化构建，需要自行修改一些配置项：
1. 需要修改 `build_docker.yml` 中的推送仓库
```yml
- name: Docker meta
id: meta
uses: docker/metadata-action@v4
with:
images: 0xjerry/chatgpt-web # 需要修改，格式 `name/repo`
```
2. 需要在仓库的 secrets 里面添加 docker hub 的 name 和 token

优化 docker 构建的镜像文件大小，添加自动化构建

---

service/package.json
service/pnpm-lock.yaml
service/src/chatgpt.ts
service/src/index.ts
src/api/index.ts
src/components/common/Setting/index.vue
src/views/chat/index.vue

1. To avoid leaking personal information, I would like to request make direct to openai.com, so a simple proxy is introduced, you could set the socks proxy by setting `SOCKS_PROXY_HOST ` and `SOCKS_PROXY_PORT` config in service/.env file.
2. Streaming mode is fixed, and it shoudl work without any issue.

feat: add proxy support and fix streaming mode

---

CONTRIBUTING.en.md
README.en.md
README.md

Translated using chatGPT so it should be easy to maintain changes to the original doc using this prompt: "Please translate this markdown into an English markdown {change text}"
Would save English speakers a trip to Google Translate when they want to see the doc

chore: added English translation for the docs

---

src/views/chat/index.vue

在开发 mac menubar 插件的时候，打开网页会被识别为移动端，无法触发 enter 发送消息的功能。因此想增加一个 ctrl+enter 发送消息。

feat: 在电脑的小窗模式打开下可以通过 ctrl+enter 发送消息

---

src/views/chat/hooks/useScroll.ts
src/views/chat/index.vue

打字机模式显示新内容时，如果此时滚动条在底部则保持滚动条始终在底部，若滚动条不在底部也不会强制滚动到底部。
目的是允许用户在生成新内容时查看以往的内容，类似官方网页 ChatGPT 的效果。#349

feat: 优化打字机模式显示新内容的逻辑

---

src/store/modules/chat/index.ts

当清空聊天记录时，同时重置历史列表的标题，以响应新聊天的更新

fix: reset history title on clear

---

src/assets/recommend.json
src/components/common/PromptStore/index.vue

如[#516](https://github.com/Chanzhaoyu/chatgpt-web/issues/516#issue-1620061293)所提到的，recommend.json里有两个repo，每个repo用的模板的字典key是不一样的。虽然只会导入一种，但如有我这样想自己做一份模板自用的可能会用错模板。导入另一种不支持的模板会导致prompt商店无法再次打开（点商店无反应），所以干脆就把两个repo的模板都支持了。
另加了点击“下载”按钮清空输入框，方便连续从不同repo导入。虽然原来也可以连续导入，点第二个repo的“+”号会自动覆盖前面输入的URL，但是在手机上如果输入框不够长看不到URL改变了（URL前半部份一样的），所以点“下载”之后自动清空输入框，再次导入再自动填入地址符合直觉。

fix: Prompt商店在线导入可以导入两种recommend.json里提到的模板 (#516)

---

src/main.ts
src/plugins/index.ts
src/plugins/scrollbarStyle.ts

To adapt the scrollbar for both light and dark mode.

fix: To make the scrollbar style compatible with naive-ui

---

service/package.json
service/pnpm-lock.yaml
service/src/chatgpt/index.ts
service/src/types.ts
src/components/common/Setting/About.vue
src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts

feat: show api balance

---

src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts
src/views/chat/components/Message/Text.vue
src/views/chat/components/Message/index.vue
src/views/chat/components/Message/style.less

最终的功能大概是这样子：
* 在弹出的菜单里添加一个选项来显示原文：
|  渲染结果 |  显示原文 |
|:--|:--|
|![image](https://user-images.githubusercontent.com/32430186/226089733-7719b414-2fbf-4892-90a1-72bb6a2671d6.png)|![image](https://user-images.githubusercontent.com/32430186/226089766-0b03452a-340b-473a-9e64-40300c1a2a98.png)|
* 输入的内容会以 Markdown 渲染（这样整体观感会和谐一些）
Closes #671

feat: 添加显示用于原文的选项

---

src/views/chat/hooks/useScroll.ts
src/views/chat/index.vue

chore: scrollToBottom 改成 scrollToBottomIfAtBottom

---

src/views/chat/index.vue

In backend with golang (like https://github.com/sashabaranov/go-openai), the responseText always has a '\n'.

fix line end with new-line in some backend

---

service/package.json
service/src/chatgpt/index.ts
service/tsup.config.ts

This pull request changes service compilation format to ESM and fix error when importing `https-proxy-agent`. `esno` should not be used in production as it hides ESM compatibility errors.
Types do not indicate this issue, I'm not sure if this is due to `esModuleInterop`, `tsup` or wrong types from `https-proxy-agent`, but it probably doesn't matter.

fix: ESM error

---

service/src/index.ts

https://docs.colyseus.io/zh_hk/colyseus/how-to/rate-limit/
使用nginx限流会只识别为服务器ip，需启用trust proxy

fix: 反向代理限流失效

---

.dockerignore

编译的时候 `.env` 文件被 `.dockerignore`  忽略了，需要排除 `.env` 文件

fix: missing VITE_GLOB_API_URL when docker build, fixed #690 #717 #

---

src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts
src/views/chat/layout/sider/index.vue

更改语言也能让“New chat”和“Prompt Store”按钮显示对应语言。

fix: 本地化侧边栏按钮

---

.github/workflows/build_docker.yml
README.md
service/.env.example
service/src/chatgpt/index.ts

添加 SOCKS_PROXY_USERNAME,  SOCKS_PROXY_PASSWORD  两个环境变量
已在本地测试

添加 socks5 代理认证

---

src/views/chat/index.vue

当前如果返回的data.text是undefined, 此时直接做连接操作，会导致得到'undefined'字符串，不符合预期
例如，在返回Unauthorized状态时，此时会返回以下回复
`
undefined
[Error: 无访问权限 | No access rights]
`

bugfix 空引用显示undefined

---

kubernetes/deploy.yaml

The original URL is outdated, here update it!

fix: Update @acheong08 Reverse Proxy URL

---

src/views/chat/index.vue

修复页面上重复执行onRegenerate操作，会丢失上下文的问题

fix: 修复页面上重复执行onRegenerate操作，会丢失上下文的问题

---

src/locales/en-US.ts
src/locales/zh-CN.ts
src/locales/zh-TW.ts

chore: 引导用户触发提示词

---

service/src/chatgpt/index.ts
service/src/chatgpt/types.ts
service/src/types.ts
src/components/common/Setting/About.vue

- 查询使用量文案同步更正，函数名同步语义化。
- 查询使用量接口支持走代理。

fix: 查询使用量支持代理&修正使用量文案

---

src/hooks/useLanguage.ts

if `setLocale('zh-CN')`, `return` should be `zhCN`, not `enUS`.

fix: default return in `useLanguange()` hook

---

CHANGELOG.md
README.md
kubernetes/deploy.yaml
package-lock.json
service/.env.example
service/src/chatgpt/index.ts

[acheong08](https://github.com/acheong08) said in this [PR](https://github.com/transitive-bullshit/chatgpt-api/pull/540#issuecomment-1514010945):
> My proxy also works now but on a different path. It might not be stable enough for consistent use though.
> 
> On another note, the unofficial APIs should probably be deprecated. OpenAI has not been happy with them and has since issued multiple takedown requests to different ones (I haven't gotten one yet though).
So,I changed the default proxy server:
https://github.com/transitive-bullshit/chatgpt-api/pull/540#issuecomment-1514010945

fix(proxy url): change ChatGPTUnofficialProxyAPI default proxy server🛩️

---

src/views/chat/components/Header/index.vue
src/views/chat/components/Message/style.less
src/views/chat/index.vue

如图左侧是之前移动端效果，右图是修改后。
1. 增大移动端代码展示框范围。
2. 修改移动端删除按钮位置

style: 优化移动端代码展示

---

README.md
service/src/chatgpt/index.ts

Add the latest and powerful `gpt-4-1106-preview` model with 128k context window(but the output is limited to 4k tokens), training data to Apr 2023, and the turbo speed :zap: 
Reference:
- https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
- https://openai.com/blog/new-models-and-developer-products-announced-at-devday#gpt-4-turbo-with-128k-context

feat: support the latest GPT-4 Turbo (gpt-4-1106-preview) model

---

service/src/chatgpt/index.ts

GPT-3.5 models with the "16k" suffix are all marked as `Legacy` now. The latest models use prefixes like 0125 and 0613, and all support a 16k context window with 4k output.
Reference:
- https://platform.openai.com/docs/models/gpt-3-5-turbo

feat: improve GPT-3.5 Turbo 16k support

---

service/package.json
service/pnpm-lock.yaml

**upgrade esno & tsx to resolve the issue.**
---
Unable to start service on Node v18.19+:
```
❯ esno ./src/index.ts        
node:internal/process/esm_loader:40
internalBinding('errors').triggerUncaughtException(
^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
at Q (file:///Users/divyansh/foo/node_modules/.pnpm/tsx@4.6.0/node_modules/tsx/dist/esm/index.mjs:1:1793)
at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
at Hooks.register (node:internal/modules/esm/hooks:168:16)
at async initializeHooks (node:internal/modules/esm/utils:167:5)
at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)
Node.js v18.20.2
```
tsx doesn't work on Node 18.19
https://github.com/privatenumber/tsx/issues/421

update esno to fix tsx issue on Node v18.19

---

README.md
README.zh.md
service/src/chatgpt/index.ts

Reference:
- https://platform.openai.com/docs/models/gpt-4o
- https://openai.com/index/hello-gpt-4o/

feat: add GPT-4o support

---

service/package-lock.json
service/package.json

Update the Node.js engine setting in service/package.json to use LTS v20 instead of the end-of-life v19. This aligns with our Dockerfile that uses node:lts-alpine, which has been a while without issues. The update also helps suppress the runtime warnings about engine compatibility:
> WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.12.2","pnpm":"9.0.4"})

chore: replace EOL Node.js v19 w/ LTS v20 in engine spec
